### ISSUE TITLE
Inaccurate "Duration" since last harvest on strategy reports tab

### ISSUE THREAD

**Issue by wavey0x** [yearn/yearn-watch-legacy#100]
every once in a while i notice a bug on yearn watch where the **duration** is displayed as a much larger time than really was since last harvest.

Still APR calculation looks correct, so i believe there must be a different "Duration" used during APR calc than what is displayed as "duration" in the UI.

For example, this harveset for MM strategy, the real duration since last harvest was about 2 weeks. However the, UI shows 785hrs here which is over one month.
![image](https://user-images.githubusercontent.com/82397455/127918449-4404cf43-e7b2-4722-b14f-d9c652d88e1a.png)

**Comment by storming0x** [comment]
Fix in PR #103 

![Screen Shot 2021-08-03 at 13 48 18](https://user-images.githubusercontent.com/6074987/128076988-ff7f085f-6665-4e87-9e03-311b2d9380d1.png)
