### ISSUE TITLE
Score / Split SingleSided - WETHSingleSided

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#110]
Create a new group and include on it the WethSingleSided strategies.

As SingleSided and WETHSingleSided are different contracts, they should have different scores, or at least not being in the same group.

![image](https://user-images.githubusercontent.com/5948309/128941798-057cb364-9933-4677-a368-a6bb1d2dbff7.png)

**Comment by storming0x** [comment]
this as per strategy meeting will be migrated so may not be as urgent, still good to track in case is not migrated

**Comment by storming0x** [comment]
created this group
