### ISSUE TITLE
Change Backend Endpoint

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#111]
Use this one: https://api.yearn.finance/v1/chains/1/vaults/all

instead of https://vaults.finance/all

Verify the field names due to there are some differences in the field names.

Example: 
This vault https://yearn.watch/vault/0xE537B5cc158EB71037D4125BDD7538421981E6AA should have 2 strategies (now the Convex strat is missing).

**Comment by storming0x** [comment]
This is high priority since it doesnt show latest strategies, also this should close this one as well

https://github.com/yearn/yearn-watch/issues/59
