### ISSUE TITLE
Add to Strategy Page list of tokens the strategy owns

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#119]
![Screen Shot 2021-08-18 at 10 30 22](https://user-images.githubusercontent.com/6074987/129936432-2dc51076-6a82-4df5-aea9-858cffa8e8d0.png)

Add a new Tab here with tokens that we can check like etherscan tab
![Screen Shot 2021-08-18 at 10 31 20](https://user-images.githubusercontent.com/6074987/129936588-b59e1ec0-8945-4b96-ba11-218ce00286ca.png)

List shows amount of tokens the strategy owns with following details per row:
-tokenname
-tokenSymbol
-balance for strat
-etherscan link for token

**Implementation details**
Probably needs etherscan api for this.
This data should not be coupled with the other data fetching, if this data is not loading the tab should show a message that it could not load the data, but the entire page should still load with the other data.

**Comment by sanvaldi** [comment]
I can work on this issue if it is available
