### ISSUE TITLE
Add TotalDebt Column in Query

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#120]
Add the TotalDebt value in USD as well column in Query table

https://yearn.watch/query/default/group/convex/

![image](https://user-images.githubusercontent.com/5948309/129407684-b8a4e7c6-379c-4ba1-a953-f513d13c1fbb.png)

Highlight row with formulas:

 if `totalAssets > 2 * totalDebt && totalAssets > Dust (MM)`  (leftover funds)

Or highlight totalDebt if : `totalDebt > 1.5 * totalAssets` (missing funds)

**Comment by uwe** [comment]
Would you mind if I add `debtOutstanding` to `ProtocolTVL`? Or should I add a new type `ProtocolDebt`?
We could also rename `ProtocolTVL` to something like `ProtocolAmounts`...

**Comment by phillip055** [comment]
Hey, is this available?

**Comment by zannis** [comment]
> Hey, is this available?

Have a draft PR open at #199 . There's one item that's not been addressed if you wanna take a look. Cheers

**Comment by phillip055** [comment]
I see it, feel free to finish it 👍
