### ISSUE TITLE
[BUG]-All experimental vaults are not loading anymore

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#122]
https://ape.tax/wether-aether

or others from ape tax. 

seems new API update no longer brings data from experimental vaults

**Comment by storming0x** [comment]
Also update subgraph URL to new deployed one?

**Comment by saltyfacu** [comment]
are you using the subgraph? you can also use this https://github.com/fameal/ape-tax/blob/master/src/vaults.json

**Comment by storming0x** [comment]
reopening this seems solution didnt work

we need to call this new api endpoint for experimentals
https://api.yearn.finance/v1/chains/1/vaults/experimental


in getVault method we need to check first for all existing prod vaults else call the experimental to get back to the functionality we had before
https://yearn.watch/vault/0x4962B6C40B5E9433E029c5c423F6b1ce7fF28b0f
