### ISSUE TITLE
Add a specific tab for gen lender strategy

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#133]
The gen lender strategy is widely used in most vaults and has special custom data that is useful to read.

Repo:

https://github.com/Grandthrax/yearnV2-generic-lender-strat

Example contract deployed
https://etherscan.io/address/0x3280499298ACe3FD3cd9C2558e9e8746ACE3E52d#code

Implementation:
-Add a new tab for strategy detail page if the strat is detected to be gen lender
-load specific gen lender data in a separate multicall to avoid coupling with main multicall
-in case of errors show 'Unable to load data-{error detail}' message in gen lender tab

This specific tab could work for other custom strategies as well if we need to check specific data about them

**Comment by storming0x** [comment]
I think this additional information is only specific to these type of strategies, so maybe logic can check if contract name is StrategyLenderYieldOptimiser to add an additional tab with its own loading like details fields components

https://yearn.watch/network/fantom/vault/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0/strategy/0x695a4a6e5888934828cb97a3a7adbfc71a70922d

Useful information to fetch from this is, i added priority for MVP vrs what can wait:

- lendStatuses (MPV)
- lentTotalAssets (MVP)
- estimatedAPR (MVP)
- estimateAdjustPosition (MVP)
- numLenders (future version)
- list the lenders based on length(num lenders) numLenders = 2 means it has lender 0 and 1 (future version)

<img width="945" alt="Screen Shot 2021-11-04 at 09 13 21" src="https://user-images.githubusercontent.com/6074987/140319497-2af7bb80-eb65-4179-a74a-9341cf97d552.png">

<img width="824" alt="Screen Shot 2021-11-04 at 09 20 53" src="https://user-images.githubusercontent.com/6074987/140320568-c3ae3ad4-79f4-409d-a5c7-535b6249a9c9.png">

**Comment by edwinzhng** [comment]
I'll take this
