### ISSUE TITLE
crvRSV total assets in $ is off by a few orders of magnitude

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#140]
<img width="1294" alt="Screen Shot 2021-08-28 at 12 17 11" src="https://user-images.githubusercontent.com/6074987/131227148-bc38e380-2dd8-40ce-89e0-ceca52760031.png">

https://yearn.watch/vault/0xC116dF49c02c5fD147DE25Baa105322ebF26Bd97

**Comment by salazarguille** [comment]
@storming0x As I can see, I think it is working now. Please could you confirm it?

![image](https://user-images.githubusercontent.com/5948309/131718394-e4c0d0c3-8a5e-48d5-832b-23b0db1954b6.png)

**Comment by storming0x** [comment]
yes closing the issue since its now fixed
