### ISSUE TITLE
[New Layout] -  Add Protocols allocation and update Strategy allocation in SingleVault Page

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#142]
New Layout desktop:

![Screen Shot 2021-08-31 at 08 29 36](https://user-images.githubusercontent.com/6074987/131521475-2e1a7f22-bd0a-42ee-b89b-b7a9c425f525.png)

Mobile:

![Screen Shot 2021-08-31 at 08 31 45](https://user-images.githubusercontent.com/6074987/131521748-65985a17-5cf7-4f73-8b81-dc24bd02f5b6.png)

**Comment by edwinzhng** [comment]
I'll take this

**Comment by edwinzhng** [comment]
Where am I supposed to pull the data for this from? I saw that we can pull protocol TVL for a query term at [yearn.watch/network/ethereum/query](https://yearn.watch/network/ethereum/query), but this seems to just search for all strategies that have the query in the name. Is there a more robust way to do this?

**Comment by edwinzhng** [comment]
Taking this
