### ISSUE TITLE
[New Layout] - Add strategy description to Single Strategy page

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#143]
NEw Layout Desktop:

![Screen Shot 2021-08-31 at 08 33 54](https://user-images.githubusercontent.com/6074987/131522199-7113429c-01fa-4a02-b370-4fb3971149ab.png)

New Layout Mobile:
![Screen Shot 2021-08-31 at 08 35 08](https://user-images.githubusercontent.com/6074987/131522281-a800becb-fe07-4a40-be92-5e8b618ff22a.png)

Data fetching example using SDK (need to add it to dependencies) and also can check on web repo how its used
https://github.com/yearn/yearn-sdk/blob/d77fc22e6a65b0c1774b08528600a048641d56bf/src/interfaces/strategy.ts#L37

**Comment by socksrust** [comment]
Whats url and figma link? Thanks

cc @storming0x

**Comment by saltyfacu** [comment]
we don't have a figma

**Comment by milkyklim** [comment]
@jaburx Figma is invite only for now. If you are willing to help hit me with your email here or on tg: @milkyklim.

**Comment by phillip055** [comment]
Is this being worked on, if not, do you mind if i pick it up? and i will it you up @milkyklim

**Comment by storming0x** [comment]
no one has been working on this @phillip055 feel free to take it, added the description example using the SDK to pull the metadata for each vault/Strategy for display

**Comment by phillip055** [comment]
@storming0x anyone i can talk to while working on this?

**Comment by phillip055** [comment]
Will split into 2 PRs, one to get description, another is with the new layout which i am getting from a designer

**Comment by storming0x** [comment]
Closing this issue
