### ISSUE TITLE
Add ape.tax vaults using the API

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-watch-legacy#148]
ape.tax has an API that would make it easier to add it to yearn-watch. The docs are here: https://github.com/fameal/ape-tax/blob/master/README.md

API URL:  https://ape.tax/api/vaults

**Comment by 0xkofee** [comment]
So I did some digging and it seems like yearn.watch calls an api in `api.yearn.finance`. It might make sense to just add the ape-tax stuff in that api so everyone has access to the ape tax vaults. I'm trying to understand where api.yearn.finance gets its data and opened up an issue in that repo to get some clarity. https://github.com/yearn/yearn-api/issues/41

**Comment by 0xkofee** [comment]
So from what I gather, yearn-api points to an s3 bucket for its data (which I believe is populated from s3 yearn-exporter) 
![image](https://user-images.githubusercontent.com/98677476/154110011-bf8f6aac-e1d7-4394-908e-c44f94f773a6.png)

now i'm investigating whether these ape vaults are already in a registry. if so, maybe the exporter just needs to include these? I spoke with @mariuspod and it sounded like s3 exporter may go away/get replaced soon. So maybe this issue needs to wait until then?

**Comment by 0xkofee** [comment]
This issue is waiting for the completion of the vault service refactor in this PR: https://github.com/yearn/yearn-watch/pull/229/files
Gonna pause on it until then.

**Comment by saltyfacu** [comment]
Sorry for the lack of response. You can check the docs for ape.tax API here: https://github.com/saltyfacu/ape-tax#use-the-api-

**Comment by 0xkofee** [comment]
@saltyfacu I think yearn watch already has the experimental vaults...

https://ape.tax/api/vaults

example:
Dai Yvault
0xdA816459F1AB5631232FE5e97a05BBBb94970c95

Curve oBTC Pool yVault
0xe9Dc63083c464d6EDcCFf23444fF3CFc6886f6FB

YFI yVault
0xdb25cA703181E7484a155DD612b06f57E12Be5F0

we didn't have to use the apis... they came from the sdk automatically

**Comment by saltyfacu** [comment]
oh my, even better if they come from the SDK :D Thanks!
