### ISSUE TITLE
Longevity: Set 5 by default

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#150]
When a group is created and it doesn't contain strategies, it displays 1 as a longevity score.

Example:

![image](https://user-images.githubusercontent.com/5948309/133654758-b888b72e-a3ee-4ecf-a491-bf2793b4958c.png)

**Comment by uwe** [comment]
Is this visible under `/risk`? How can I access this? Even after login I get `Failed to load the scores!`

**Comment by salazarguille** [comment]
@uwe thanks for your PRs. That URL is private and required some approvals to get access.

**Comment by storming0x** [comment]
> Is this visible under `/risk`? How can I access this? Even after login I get `Failed to load the scores!`

these are now visible

[yearn.watch risk score](https://yearn.watch/network/ethereum/risk)

**Comment by uwe** [comment]
Sorry, please don't wait for a PR from me.

**Comment by kyhoon** [comment]
I had a take on this issue on #261
