### ISSUE TITLE
Add Network Label on Top

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#166]

**Comment by haechi00** [comment]
Done it! https://github.com/yearn/yearn-watch/pull/178 :)


<img width="700" alt="Screenshot 2021-11-21 at 20 15 36" src="https://user-images.githubusercontent.com/88509054/142775840-ec956970-bd07-4e0a-bd2b-4b5d23fa6947.png">

**Comment by storming0x** [comment]
closed by #178
