### ISSUE TITLE
Refactor: Use Multicall to Get HealthCheck and DoHealthCheck

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#174]
Now it is using the subgraph to query the health check info.

Since there are some issues with the events in the contract, we would need to query these values from the contract directly.

**Comment by uwe** [comment]
Should this work be based on #82?

EDIT: Just saw, there are many merge conflicts in this branch.

**Comment by salazarguille** [comment]
Exactly, working on it now

**Comment by storming0x** [comment]
Needs to refactor existing calls from healthchecks to be done with multicall field instead

**Comment by magikadev** [comment]
Resolved it on https://github.com/yearn/yearn-watch/pull/179
