### ISSUE TITLE
Strategies not showing up in fantom risk dashboard

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#186]
This strategy:
https://yearn.watch/network/fantom/vault/0x0A0b23D9786963DE69CB2447dC125c49929419d8/strategy/0x24bc86a808d45f0aad8008bd3ac2d9356007e833

Does not show up in the list or accounting in the risk dashboard.
https://yearn.watch/network/fantom/risk

Expectation:

Degenbox should show up in risk dashboard table and total TVL.

**Comment by rareweasel** [comment]
@magic990619 will work on this issue.

**Comment by magikadev** [comment]
👌

**Comment by magikadev** [comment]
![image](https://user-images.githubusercontent.com/46446076/160501882-eeb66a17-c30d-496d-b564-ff8931954c6a.png)

It is showing on fantom risk dashboard now.
https://ftmscan.com/address/0x24BC86a808D45f0AAd8008bd3ac2D9356007e833#readContract
Kashi Lender
