### ISSUE TITLE
Create data hook for strategy report

### ISSUE THREAD

**Issue by phillip055** [yearn/yearn-watch-legacy#210]
an enhancement where we move strategy report data logic into a hook, or is there a reason we need StrategyReportProvider 🤔

**Comment by edwinzhng** [comment]
yeah this could be a hook, the provider was just to do some caching so we don't refetch reports. we can probably cache this in a hook instead

**Comment by magikadev** [comment]
https://github.com/yearn/yearn-watch/pull/229
