### ISSUE TITLE
Update the groupings for updated strategy names (ssb and ssbeet)

### ISSUE THREAD

**Issue by magikadev** [yearn/yearn-watch-legacy#221]
Some strategy names have been updated. Strategy names started with `SSB` have been updated to `SSBv2`. And beethoven versions are now called `ssbeetV2.1`. 
To track these changes, we need to update the groupings.

Expectation:
Update the groupings for ssb and ssbeet on fantom.

**Comment by storming0x** [comment]
To do this we need to go to this file and add in nameLike property the string to match for name of the strategies

https://github.com/yearn/yearn-watch/blob/08d2353d1b6e8cee06ee57df4f9fea326c4e01e2/src/utils/config/risk-framework.json#L414

The group names are SSB = single sided balancer
SSBBeet = Single Sided Beethoven

Expectation after change:
on these pages
ethereum ->https://yearn.watch/network/ethereum/risk
fantom -> https://yearn.watch/network/fantom/risk

The "others" grouping should show 0$ TVL assigned, and corresponding groups single sided balancer and single sided Beethoven should show an increase of TVL when adding the strategies TVL
