### ISSUE TITLE
Migrate mainnet to new subgraph URL

### ISSUE THREAD

**Issue by edwinzhng** [yearn/yearn-watch-legacy#231]
Mainnet currently uses the old hosted subgraph: `https://api.thegraph.com/subgraphs/name/salazarguille/yearn-vaults-v2-subgraph-mainnet`

We should change this to the new version `https://thegraph.com/explorer/subgraph?id=0xf50b705e4eaba269dfe954f10c65bd34e6351e0c-0&version=0xf50b705e4eaba269dfe954f10c65bd34e6351e0c-0-0&view=Overview`

**Comment by kevoconnell** [comment]
ill take this! I think I need write access to make a pr though

**Comment by edwinzhng** [comment]
Hey @MrKevinOConnell you'll need to fork the repo and then you can make PRs. Also we'd need to get API keys for the subgraph and read them via env variables (@rareweasel should know more about doing this for production), for the dev API key, I can ask if Yearn has one we can use

**Comment by edwinzhng** [comment]
Actually there are a couple security issues we need to iron out before we can migrate things over. I'll update this issue later
