### ISSUE TITLE
[New Layout] Make font styles

### ISSUE THREAD

**Issue by phillip055** [yearn/yearn-watch-legacy#238]
Given the new ui, figma, set font on MUI themes

https://mui.com/customization/typography/#variants

**Comment by sanvaldi** [comment]
I can grab this issue

**Comment by sanvaldi** [comment]
Just to be sure this is the approach we want.

1. set all fonts on muiTheme

<img width="776" alt="Screen Shot 2022-03-07 at 9 31 20 PM" src="https://user-images.githubusercontent.com/43012589/157141760-01c16a0a-1682-4fe7-b9e3-5161793a54f6.png">

2. replace all styled Typography components with its respective variant. e.g:

<img width="373" alt="Screen Shot 2022-03-07 at 9 36 09 PM" src="https://user-images.githubusercontent.com/43012589/157142302-98406d9a-5f0d-4945-aab9-8bc9ddbda32e.png">

**Comment by saltyfacu** [comment]
Old and we have a new design. Will close.
