### ISSUE TITLE
Bug: Risk Framework. Others group missing some strategies and  TVL

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#250]
https://yearn.watch/network/fantom/vault/0x0fBbf9848D969776a5Eb842EdAfAf29ef4467698/strategy/0xade3bac94177295329474aad6a253bae979bfa68

This strategy attached to Boo Vault is expected to show in the others group here with TVL:

https://yearn.watch/network/fantom/risk
![Screen Shot 2022-03-08 at 10 47 19](https://user-images.githubusercontent.com/6074987/157285124-e61241de-2197-41fe-8200-f261474cbced.png)

**Comment by kyhoon** [comment]
I have added the 'all' keyword to the json file in #258, the page should now show 98 strategies for the Others group.
Let me know if this is not the intended result
