### ISSUE TITLE
BUG: others group in fantom shows TVL from strategies in other groups

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#263]
https://yearn.watch/network/fantom/risk

<img width="1465" alt="Screen Shot 2022-03-16 at 23 01 30" src="https://user-images.githubusercontent.com/6074987/158740552-91aa9790-25f1-4500-9eda-f888a4b7d791.png">

Others group is showing TVL, seems the strategy list are strats that are accounted for in others group so filter or something in the logic is mislabeling as others.

https://yearn.watch/network/fantom/query/default/group/all/?exclude=StrategyLenderYieldOptimiser&exclude=GenLevCompV3NoFlash&exclude=rebalancer&exclude=SingleSidedBeethoven&exclude=ssbeetV2&exclude=ssbeetV2.1&exclude=vedao&exclude=0xdao&exclude=solidexjoint&exclude=singleassetsolidexLP&exclude=singleassetsolidexLPwitharb

Expectation:

If strategy grouping has correct setup for fantom network and others is correctly excluding the same filter, the strategies for that group should not appear and be accounted in TVL under the Others group.

**Comment by kyhoon** [comment]
Possibly also related to #254 

I have looked into this for a bit and found that the registered address in the [AddressesGeneratorV2Vaults contract](https://ftmscan.com/address/0x8ca27a3ab8917a033f278d20135d2467faa099ba#code) currently returns a total of 55 strategies, whereas the sdk instance returns a total of 129 on the fantom chain.

The Others group is currently pulling the strategies from the sdk, thus all the missing strategies seem to be classified as the Others group. I believe the strategies in Solidex Joint group (#254) are currently also being counted as the Others.

A quick fix to this might be to pull all data from our sdk atm.

**Comment by storming0x** [comment]
yes, maybe just for fantom in that case. My concern is if we introduce a change that causes a regression on ethereum network to fix fantom risk.

Can you validate in local for change?

**Comment by kyhoon** [comment]
Tried to fix this and #254 on #264

**Comment by saltyfacu** [comment]
@storming0x can you confirm if this is solved by the PR?

**Comment by storming0x** [comment]
@saltyfacu still not working

https://yearn.watch/network/fantom/risk/

others group is still floating around in heat map
![Screen Shot 2022-03-22 at 09 05 59](https://user-images.githubusercontent.com/6074987/159513564-869d6faa-3633-4d6a-8c3d-7ddb3d6efa7f.png)


https://yearn.watch/network/fantom/query/default/group/all/?exclude=StrategyLenderYieldOptimiser&exclude=GenLevCompV3NoFlash&exclude=rebalancer&exclude=SingleSidedBeethoven&exclude=ssbeetV2&exclude=ssbeetV2.1&exclude=vedao&exclude=0xdao&exclude=solidexjoint&exclude=veLp_Solidex&exclude=veLp_arb_Solidex&exclude=fbeetscompounder

**Comment by kyhoon** [comment]
To fully solve this I believe we should handle all the strategies that are missing (related to #248) or not excluded correctly,
I will look into this soon if not handled by someone else in the meantime

**Comment by storming0x** [comment]
> To fully solve this I believe we should handle all the strategies that are missing (related to #248) or not excluded correctly, I will look into this soon if not handled by someone else in the meantime

sync w @rareweasel which is also handling the list in tg

**Comment by magikadev** [comment]
![image](https://user-images.githubusercontent.com/46446076/159809708-aa3c5714-3129-4b8a-9aa4-c3ed4238dbb5.png)

We have alinged all missed groups.

Thanks to @rareweasel @storming0x @saltyfacu @kyhoon @major-eth
