### ISSUE TITLE
Hedgil Spooky Joint provider: Create new Fantom Group

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-watch-legacy#293]
"name": "IL-Hedge Hedgil Spooky Liquidity Provider"
"network":"fantom"
"id": "tohedgilspookyjoint",
"codeReviewScore": 2,
"testingScore": 3,
"auditScore": 5,
"protocolSafetyScore": 2,
"complexityScore": 4,
"teamKnowledgeScore": 3
"nameLike": ["ToHedgilSpookyJoint"],

Also, add this one in the Others group.

Note:
Please, verify that this group has these two strategies (TVL: USD ~2.09 MM):

[Strategy_ProviderOfUSDCToHedgilSpookyJoint(USDC-WFTM) (0x9978...11fa)](https://yearn.watch/network/fantom/vault/0xEF0210eB96c7EB36AF8ed1c20306462764935607/strategy/0x99781f4324cf60d96195276822d2518fc85c11fa)

[Strategy_ProviderOfWFTMToHedgilSpookyJoint(USDC-WFTM) (0x32d1...9a1a)](https://yearn.watch/network/fantom/vault/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0/strategy/0x32d1bc9133f46e4442b9666bbc361bb90ce49a1a)

**Comment by magikadev** [comment]
![image](https://user-images.githubusercontent.com/46446076/160838828-d680bd87-3047-4e86-a913-37144f2d3a6e.png)
