### ISSUE TITLE
Remove Group SSBv2

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-watch-legacy#321]
Once Group SSBv3 includes all the strategies (5) and and TVL for group SSBv2 is 0, please remove group [SSBv2](https://github.com/yearn/yearn-watch/blob/master/src/utils/config/risk-framework.json#L403-L418) and also from the Others group

**Comment by rareweasel** [comment]
SSBv3 is already tracked in the Risk Framework (group "Single Sided Balancer v3")

**Comment by magikadev** [comment]
OK, Let's remove it.
