### ISSUE TITLE
Update Convex (Ethereum) Group Scores

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-watch-legacy#334]
Update the score for [this (Convex) group](https://github.com/yearn/yearn-watch-legacy/blob/master/src/utils/config/risk-framework.json#L19-L34)

"id": "convex",
"network": "ethereum",
"label": "Convex",
"codeReviewScore": 3,
"testingScore": 3,
"auditScore": 5,
"protocolSafetyScore": 2,
"complexityScore": 2,
"teamKnowledgeScore": 1,

**Comment by CutupAngel** [comment]
@magic990619  Can you check on this [PR](https://github.com/yearn/yearn-watch-legacy/pull/335)?
cc @rareweasel

**Comment by rareweasel** [comment]
Done [here](https://github.com/yearn/yearn-watch-legacy/pull/335)
