### ISSUE TITLE
Some Reports are not loading

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#53]
Couple examples where i'm not seeing reports showing up:

1. https://yearn-hub.vercel.app/strategy/WBTC%20yVault/0x6598d4366D5A45De4Bf2D2468D877E0b6436Ae76

2. https://yearn-hub.vercel.app/strategy/WBTC%20yVault/0xb85413f6d07454828eAc7E62df7d847316475178

Research if this is a subgraph issue or a mapping issue

**Comment by salazarguille** [comment]
It looks like they weren't registered

**Comment by storming0x** [comment]
> It looks like they weren't registered

created this issue in Subgraph repo:

https://github.com/yearn/yearn-vaults-v2-subgraph/issues/89

**Comment by salazarguille** [comment]
Please @storming0x , could you verify it now? It should be working.

**Comment by storming0x** [comment]
its closed with subgraph fix
