### ISSUE TITLE
Show Average APR for Strategy on Vault Page Strategies List

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#60]
This would need need caching/memoize of subgraph report and refactoring of the mapping to support calling multiple strategies, since we are calling the same method but not showing anything more than the APR, and if later user navigates to REports page it should cache the results

![Screen Shot 2021-06-11 at 16 49 12](https://user-images.githubusercontent.com/6074987/121755714-21de6580-cad5-11eb-8469-5bc94f270287.png)

**Comment by storming0x** [comment]
Component involve:

https://github.com/yearn/yearn-watch/tree/master/src/components/app/SingleVault

ideally we use the same util fetching calls to get the average apr that we use in singleStrategy.tsx to show it as part of the list

![Screen Shot 2021-10-12 at 17 50 42](https://user-images.githubusercontent.com/6074987/137044022-3b32181e-fb93-43cd-b8d7-e2ee581376cf.png)

The average APR would be added to the card with general information of the strategy on single vault page from strategy list component

https://github.com/yearn/yearn-watch/blob/master/src/components/app/StrategiesList/index.tsx

https://yearn.watch/network/ethereum/vault/0xdA816459F1AB5631232FE5e97a05BBBb94970c95/strategy/0x3280499298ACe3FD3cd9C2558e9e8746ACE3E52d

Things to think about:
- how to add this extra data fetching from subgraph to vaults single page without affecting overall network time. Ideally this is fetched async, but doesnt stop the page from rendering when the rest of the data is available. we use this pattern in some components to fetch non critical extra data.

**Comment by edwinzhng** [comment]
Mind if I take this issue?

**Comment by storming0x** [comment]
great work @edwinzhng i will review your code soon
