### ISSUE TITLE
No reports on the yvLINK strategies

### ISSUE THREAD

**Issue by poolpitako** [yearn/yearn-watch-legacy#62]
Example:
https://yearn-hub.vercel.app/strategy/LINK%20yVault/0x328C39cD6cFD7DA6E64a5efdEF23CD63892f76A0

We recently harvested all but vesper strats in:
https://etherscan.io/tx/0xaf74af129b8990107ffe333a611929c92dc1a5bdc5a5b1cee7976c43f913d489

I believe connecting 035 strats into 042 vaults might break your reports 🤷

**Comment by storming0x** [comment]
it may be related to this same issue here:

#53

**Comment by salazarguille** [comment]
@poolpitako 

Please, correct me if I am wrong.

This TX https://etherscan.io/tx/0xaf74af129b8990107ffe333a611929c92dc1a5bdc5a5b1cee7976c43f913d489 emitted a `Harvested` event for the strategy `StrategyMakerWBTCDAIDelegate` (not for `StrategyLenderYieldOptimiser`). 
The report for that TX is displayed in this link (tab `Reports`) https://yearn.watch/strategy/WBTC%20yVault/0x04A508664B053E0A08d5386303E649925CBF763c

Please, if you have any harvest tx links for any other strategy, send me them. So, I can review them in the subgraph.

**Comment by poolpitako** [comment]
Talked to @salazarguille about this today. Adding some info here for future reference:
Etherscan doesn't show the event, but the events are there.

They are shown here: https://ethtx.info/mainnet/0xaf74af129b8990107ffe333a611929c92dc1a5bdc5a5b1cee7976c43f913d489

The strategies which events are not listed in etherscan are clones.

**Comment by poolpitako** [comment]
works! thanks

**Comment by salazarguille** [comment]
Great, closing issue.
