### ISSUE TITLE
Profit misreported on yvWBTC Maker

### ISSUE THREAD

**Issue by wavey0x** [yearn/yearn-watch-legacy#64]
For Maker WBTC strat [on yearn hub reports tab](https://yearn-hub.vercel.app/strategy/WBTC%20yVault/0x04A508664B053E0A08d5386303E649925CBF763c), I notice a lot of reports which show `totalprofit = 7` or `totalprofit = 6`.
It seemed suspicious, so I check ethtx.info to confirm it is incorrect.

### Example
tx hash = `0xfd6e49a6e6c7f2f55dde8432810dcb5785293b55d3451cd7e41391ef56ef15f5`
See Harvested event [at this link](https://ethtx.info/mainnet/0xfd6e49a6e6c7f2f55dde8432810dcb5785293b55d3451cd7e41391ef56ef15f5) showing profit as `4258165`

**Comment by salazarguille** [comment]
```
{
  harvests(where: {transaction: "0xfd6e49a6e6c7f2f55dde8432810dcb5785293b55d3451cd7e41391ef56ef15f5-132"}) {
    id
    vault {
      id
      transaction {
        hash
        event
        blockNumber
      }
      shareToken { symbol }
    }
    profit
    loss
    strategy {
      name
    }
    transaction {
      id
    }
  }
}
```
