### ISSUE TITLE
Add support to detect keepCRV field

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#75]
https://etherscan.io/address/0xfb0702469A1a0440E87C06605461E8660FD0F43d#readContract

Some contract have keepCRV setting that we want to track and monitor, this is another field that is not generic so we need a similar approach to #74 for this field.

Ideally the implementation can pave the road to making it easy to add new fields as we need to monitor, in this case it may be solved by checking a regex or CRV string in strategy name to detect that is most likely to have the field

**Comment by storming0x** [comment]
Is this something that can be done with @x48-crypto strategyhelper contract?, main issue when pulling data from strategies is that this field is not always available, it depends on each contract. The good thing is that the field is named consistently as keepCRV

**Comment by ghost** [comment]
@storming0x You can kind of pull this data with strategy helper, but there seems to be a bug in the helper for fields that don't exist. You can call the query below reliably (give me all strategies where keepCRV() is greater than or equal to 1000), but for some reason it's failing with zero values.

```
addresses_provider = Contract("0x9be19Ee7Bc4099D62737a7255f5c227fBcd6dB93")
strategies_helper = Contract(addresses_provider.addressById("HELPER_STRATEGIES"))
strategies_helper.assetsStrategiesAddressesByFilter([["VALUE", "1000", "DECIMAL"], ["KEY", "keepCRV", "DECIMAL"], ["OPERATOR", "GTE"]])
```

If you need interface detection you could use `implementsMethod(address,string)` here:
https://gist.github.com/x48-crypto/ebae75940593059c8841c5fb19ae599b

Though, this contract is not deployed at the moment.
