### ISSUE TITLE
Allow access to an strategy using /vaultAddress/strategyAddress

### ISSUE THREAD

**Issue by salazarguille** [yearn/yearn-watch-legacy#86]
Allow access to the strat info with the vault address (not name) and strategy address.

Now: 
https://yearn.watch/strategy/Curve%20USDP%20Pool%20yVault/0x94fA3A90E680f6b866545C904D1dc9DEe6416de9

Expected:
yearn.watch/{vaultAddress}/strategy/{strategyAddress}

**Comment by storming0x** [comment]
maybe this should be yearn.watch/{vaultAddress}/strategy/{strategyAddress} wdty @salazarguille ?

**Comment by salazarguille** [comment]
Yes, makes sense. I will update the issue

**Comment by salazarguille** [comment]
Solved in #89
