### ISSUE TITLE
Add Vault Name to Strategy Page header

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch-legacy#98]
![Screen Shot 2021-07-26 at 11 41 42](https://user-images.githubusercontent.com/6074987/127034824-99525601-817a-4395-b353-b9945e0e9eac.png)
Add to strategy page the vault name for easier navigation since its no longer part of breadcrumb

**Comment by salazarguille** [comment]
FYI: We should add a call to the vault contract to get the name. At this point, we only have all the strat info (including the vault address)

**Comment by storming0x** [comment]
closed by #144
